import { createContext, useContext, useState, ReactNode, useCallback } from "react";

export type Lang = "en" | "si" | "ta";

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    return (localStorage.getItem("lang") as Lang) || "en";
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("lang", l);
  };

  const t = useCallback(
    (key: string): string => {
      const translation = translations[lang]?.[key];
      return translation || translations["en"]?.[key] || key;
    },
    [lang]
  );

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);

// ─── Translation dictionaries ───

const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Nav
    "nav.home": "Home",
    "nav.subjects": "Subjects",
    "nav.practice": "Practice",
    "nav.pastPapers": "Past Papers",
    "nav.challenge": "Challenge",
    "nav.leaderboard": "Leaderboard",
    "nav.analytics": "Analytics",
    "nav.settings": "Settings",

    // Dashboard
    "dashboard.greeting": "Good morning",
    "dashboard.todaysPlan": "Today's Plan",
    "dashboard.questionsRemaining": "questions remaining",
    "dashboard.startSession": "Start Today's Session",
    "dashboard.subjectUniverse": "Subject Universe",
    "dashboard.subjectUniverseDesc": "Your subjects orbit around your progress",
    "dashboard.todaysQuestions": "Today's Questions",
    "dashboard.weeklyAccuracy": "Weekly Accuracy",
    "dashboard.currentStreak": "Current Streak",
    "dashboard.nationalRank": "National Rank",
    "dashboard.recentActivity": "Recent Activity",
    "dashboard.needsAttention": "Needs Attention",
    "dashboard.yourSubjects": "Your Subjects",
    "dashboard.practiceNow": "Practice Now →",
    "dashboard.reviewTopics": "Review Topics →",
    "dashboard.days": "days",
    "dashboard.daysToExam": "Days to A/L Exam",
    "dashboard.dayStreak": "day streak",

    // Subjects
    "subject.combinedMaths": "Combined Maths",
    "subject.physics": "Physics",
    "subject.chemistry": "Chemistry",
    "subject.biology": "Biology",
    "subject.integration": "Integration",
    "subject.wavesOptics": "Waves & Optics",
    "subjects.desc": "Explore your A/L subjects and track chapter-level progress",
    "subjects.totalSubjects": "Total Subjects",
    "subjects.totalChapters": "Total Chapters",
    "subjects.totalQuestions": "Total Questions",
    "subjects.overallAccuracy": "Overall Accuracy",
    "subjects.chapters": "chapters",
    "subjects.questions": "questions",

    // Past Papers
    "pastPapers.title": "Past Papers",
    "pastPapers.desc": "Practice with real A/L exam papers from previous years",
    "pastPapers.totalPapers": "Total Papers",
    "pastPapers.attempted": "Attempted",
    "pastPapers.avgScore": "Avg. Score",
    "pastPapers.search": "Search papers by subject, year, or type...",
    "pastPapers.starred": "Starred",
    "pastPapers.subject": "Subject",
    "pastPapers.year": "Year",
    "pastPapers.type": "Type",
    "pastPapers.start": "Start",
    "pastPapers.retry": "Retry",
    "pastPapers.review": "Review",
    "pastPapers.noResults": "No papers found matching your filters",
    "pastPapers.papers": "papers",
    "pastPapers.questions": "questions",

    // Challenge
    "challenge.title": "Challenge Mode",
    "challenge.desc": "Battle other students in real-time knowledge duels",
    "challenge.findOpponent": "Find Opponent",
    "challenge.searching": "Searching for a worthy opponent...",
    "challenge.opponentFound": "Opponent found! Preparing battle...",
    "challenge.1v1": "1v1 Knowledge Battle",
    "challenge.you": "You",
    "challenge.opponent": "Opponent",
    "challenge.question": "Question",
    "challenge.victory": "Victory!",
    "challenge.defeat": "Defeat",
    "challenge.draw": "Draw!",
    "challenge.outstanding": "Outstanding performance!",
    "challenge.evenlyMatched": "Evenly matched!",
    "challenge.betterLuck": "Better luck next time!",
    "challenge.playAgain": "Play Again",
    "challenge.backToDashboard": "Back to Dashboard",
    "challenge.ratingPoints": "Rating Points",
    "challenge.xpEarned": "XP Earned",

    // Leaderboard
    "leaderboard.title": "Leaderboard",
    "leaderboard.nationalTitle": "National Leaderboard",
    "leaderboard.compete": "Compete with 18,429 students across Sri Lanka",
    "leaderboard.desc": "See how you rank among Sri Lanka's top A/L students",
    "leaderboard.national": "National",
    "leaderboard.school": "School",
    "leaderboard.friends": "Friends",
    "leaderboard.searchStudents": "Search students...",
    "leaderboard.rank": "Rank",
    "leaderboard.student": "Student",
    "leaderboard.score": "Score",
    "leaderboard.accuracy": "Accuracy",
    "leaderboard.streak": "Streak",

    // Settings
    "settings.title": "Settings",
    "settings.desc": "Manage your profile, preferences, and notifications",
    "settings.profile": "Profile",
    "settings.alerts": "Alerts",
    "settings.theme": "Theme",
    "settings.privacy": "Privacy",
    "settings.fullName": "Full Name",
    "settings.email": "Email",
    "settings.school": "School",
    "settings.phone": "Phone",
    "settings.stream": "Stream",
    "settings.year": "Year",
    "settings.saveChanges": "Save Changes",
    "settings.savePreferences": "Save Preferences",
    "settings.applyChanges": "Apply Changes",
    "settings.studyReminders": "Study Reminders",
    "settings.studyRemindersDesc": "Control when and how we nudge you",
    "settings.dailyReminder": "Daily study reminder",
    "settings.dailyReminderDesc": "Get a push at your preferred study time",
    "settings.weeklyReport": "Weekly progress report",
    "settings.weeklyReportDesc": "Summary of your week's performance",
    "settings.socialCompetitive": "Social & Competitive",
    "settings.socialCompetitiveDesc": "Stay in the loop with friends and rivals",
    "settings.challengeInvites": "Challenge invites",
    "settings.challengeInvitesDesc": "When someone challenges you to a battle",
    "settings.leaderboardUpdates": "Leaderboard updates",
    "settings.leaderboardUpdatesDesc": "When your rank changes significantly",
    "settings.deliveryChannels": "Delivery Channels",
    "settings.emailNotifs": "Email notifications",
    "settings.pushNotifs": "Push notifications",
    "settings.soundEffects": "Sound effects",
    "settings.themeLabel": "Theme",
    "settings.themeDesc": "Choose your visual vibe",
    "settings.dark": "Dark",
    "settings.darkDesc": "Easy on the eyes",
    "settings.light": "Light",
    "settings.lightDesc": "Classic bright mode",
    "settings.system": "System",
    "settings.systemDesc": "Follow device settings",
    "settings.language": "Language",
    "settings.languageDesc": "Select your preferred language for questions and UI",
    "settings.privacyVisibility": "Privacy & Visibility",
    "settings.privacyDesc": "Control who sees your data",
    "settings.showProfile": "Show profile on leaderboard",
    "settings.showProfileDesc": "Others can see your name and school",
    "settings.showStreak": "Display streak publicly",
    "settings.showStreakDesc": "Show your study streak on your profile",
    "settings.allowChallenges": "Allow challenge invites",
    "settings.allowChallengesDesc": "Let other students challenge you",
    "settings.shareAnalytics": "Share analytics with teachers",
    "settings.shareAnalyticsDesc": "Your school teachers can view your progress",
    "settings.dangerZone": "Danger Zone",
    "settings.dangerDesc": "These actions are irreversible",
    "settings.resetProgress": "Reset Progress",
    "settings.deleteAccount": "Delete Account",

    // SubjectDetail
    "subjectDetail.stream": "Stream",
    "subjectDetail.questions": "questions",
    "subjectDetail.accuracy": "accuracy",
    "subjectDetail.overview": "Overview",
    "subjectDetail.chapters": "Chapters",
    "subjectDetail.practice": "Practice",
    "subjectDetail.pastPapers": "Past Papers",
    "subjectDetail.notes": "Notes",
    "subjectDetail.topicMasteryMap": "Topic Mastery Map",
    "subjectDetail.accuracyLast7": "Accuracy — Last 7 Days",
    "subjectDetail.subTopics": "sub-topics",
    "subjectDetail.configurePractice": "Configure Practice Session",
    "subjectDetail.chapter": "Chapter",
    "subjectDetail.allChapters": "All Chapters",
    "subjectDetail.difficulty": "Difficulty",
    "subjectDetail.questionType": "Question Type",
    "subjectDetail.mixed": "Mixed",
    "subjectDetail.questionsCount": "Questions",
    "subjectDetail.timedMode": "Timed Mode",
    "subjectDetail.beginPractice": "Begin Practice",
    "subjectDetail.examination": "A/L Examination",
    "subjectDetail.startExam": "Start Exam",
    "subjectDetail.aiNotesSoon": "AI-generated summaries and community notes coming soon",
    "subjectDetail.qs": "Qs",

    // Practice
    "practice.questionOf": "Question",
    "practice.of": "of",
    "practice.excellentWork": "Excellent Work!",
    "practice.goodJob": "Good Job!",
    "practice.keepPracticing": "Keep Practicing!",
    "practice.accuracy": "Accuracy",
    "practice.correct": "Correct",
    "practice.wrong": "Wrong",
    "practice.backToDashboard": "Back to Dashboard",
    "practice.tryAgain": "Try Again",
    "practice.explanation": "Explanation",
    "practice.correctExplanation": "Correct! Well done. This is the right approach to solving this problem.",
    "practice.wrongExplanation": "Review this topic for better understanding.",
    "practice.correctAnswerIs": "The correct answer is",
    "practice.flagForReview": "Flag for Review",
    "practice.nextQuestion": "Next Question",
    "practice.finish": "Finish",

    // Analytics
    "analytics.title": "Analytics",
    "analytics.desc": "Your performance over the last 30 days",
    "analytics.questionsAnswered": "Questions Answered",
    "analytics.overallAccuracy": "Overall Accuracy",
    "analytics.studyHours": "Study Hours",
    "analytics.subjectsImproved": "Subjects Improved",
    "analytics.accuracyBySubject": "Accuracy by Subject",
    "analytics.dailyAccuracyTrend": "Daily Accuracy Trend",
    "analytics.topicMastery": "Topic Mastery",
    "analytics.studyActivity": "Study Activity",
    "analytics.examReadiness": "Exam Readiness",
    "analytics.examReady": "Exam Ready",
    "analytics.predictedGrades": "Predicted Grades",
    "analytics.confidence": "confidence",
    "analytics.less": "Less",
    "analytics.more": "More",
    "analytics.sessions": "sessions",

    // Dashboard extra
    "dashboard.missedSessions": "You've missed 3 sessions on",
    "dashboard.chapter4": "Chapter 4",
    "dashboard.accuracyDropped": "accuracy dropped to 69%",
    "dashboard.downFromLastWeek": "Down from 75% last week",
    "dashboard.completedPhysics": "Completed Physics MCQ set — 18/20 correct",
    "dashboard.newPersonalBest": "New personal best in Chemistry! 94% accuracy",
    "dashboard.unlockedBadge": "Unlocked: 'Week Warrior' badge",
    "dashboard.hoursAgo": "2h ago",
    "dashboard.yesterday": "Yesterday",
    "dashboard.daysAgo": "3 days ago",
    "dashboard.paper1MCQs": "2022 Paper 1 MCQs",

    // Leaderboard extra
    "leaderboard.allSubjects": "All Subjects",
    "leaderboard.you": "You",
    "leaderboard.noData": "No rankings yet. Start practicing to appear on the leaderboard!",

    // Common
    "common.all": "All",
    "common.easy": "Easy",
    "common.medium": "Medium",
    "common.hard": "Hard",
    "common.mcq": "MCQ",
    "common.structured": "Structured",
    "common.essay": "Essay",
    "common.english": "English",
    "common.sinhala": "Sinhala",
    "common.tamil": "Tamil",
  },

  si: {
    // Nav
    "nav.home": "මුල් පිටුව",
    "nav.subjects": "විෂයයන්",
    "nav.practice": "පුහුණුව",
    "nav.pastPapers": "පසුගිය ප්‍රශ්න පත්‍ර",
    "nav.challenge": "අභියෝගය",
    "nav.leaderboard": "ලීඩර්බෝඩ්",
    "nav.analytics": "විශ්ලේෂණ",
    "nav.settings": "සැකසුම්",

    // Dashboard
    "dashboard.greeting": "සුබ උදෑසනක්",
    "dashboard.todaysPlan": "අද දවසේ සැලැස්ම",
    "dashboard.questionsRemaining": "ප්‍රශ්න ඉතිරිව ඇත",
    "dashboard.startSession": "අද දවසේ සැසිය ආරම්භ කරන්න",
    "dashboard.subjectUniverse": "විෂය විශ්වය",
    "dashboard.subjectUniverseDesc": "ඔබේ විෂයයන් ඔබේ ප්‍රගතිය වටා කැරකෙයි",
    "dashboard.todaysQuestions": "අද ප්‍රශ්න",
    "dashboard.weeklyAccuracy": "සතිපතා නිරවද්‍යතාව",
    "dashboard.currentStreak": "වත්මන් streak",
    "dashboard.nationalRank": "ජාතික ශ්‍රේණිගත කිරීම",
    "dashboard.recentActivity": "මෑත ක්‍රියාකාරකම්",
    "dashboard.needsAttention": "අවධානය අවශ්‍යයි",
    "dashboard.yourSubjects": "ඔබේ විෂයයන්",
    "dashboard.practiceNow": "දැන් පුහුණු වන්න →",
    "dashboard.reviewTopics": "මාතෘකා නැවත බලන්න →",
    "dashboard.days": "දින",
    "dashboard.daysToExam": "උසස් පෙළ විභාගයට දින",
    "dashboard.dayStreak": "දින streak",

    // Subjects
    "subject.combinedMaths": "සංයුක්ත ගණිතය",
    "subject.physics": "භෞතික විද්‍යාව",
    "subject.chemistry": "රසායන විද්‍යාව",
    "subject.biology": "ජීව විද්‍යාව",
    "subject.integration": "සමාකලනය",
    "subject.wavesOptics": "තරංග සහ ප්‍රකාශ විද්‍යාව",
    "subjects.desc": "ඔබේ උසස් පෙළ විෂයයන් ගවේෂණය කර පරිච්ඡේද මට්ටමේ ප්‍රගතිය නිරීක්ෂණය කරන්න",
    "subjects.totalSubjects": "මුළු විෂයයන්",
    "subjects.totalChapters": "මුළු පරිච්ඡේද",
    "subjects.totalQuestions": "මුළු ප්‍රශ්න",
    "subjects.overallAccuracy": "සමස්ත නිරවද්‍යතාව",
    "subjects.chapters": "පරිච්ඡේද",
    "subjects.questions": "ප්‍රශ්න",

    // Past Papers
    "pastPapers.title": "පසුගිය ප්‍රශ්න පත්‍ර",
    "pastPapers.desc": "පසුගිය වසරවල සැබෑ උසස් පෙළ විභාග ප්‍රශ්න පත්‍ර සමඟ පුහුණු වන්න",
    "pastPapers.totalPapers": "මුළු ප්‍රශ්න පත්‍ර",
    "pastPapers.attempted": "උත්සාහ කළ",
    "pastPapers.avgScore": "සාමාන්‍ය ලකුණ",
    "pastPapers.search": "විෂය, වර්ෂය, හෝ වර්ගය අනුව සොයන්න...",
    "pastPapers.starred": "තරු සලකුණු කළ",
    "pastPapers.subject": "විෂය",
    "pastPapers.year": "වර්ෂය",
    "pastPapers.type": "වර්ගය",
    "pastPapers.start": "ආරම්භ කරන්න",
    "pastPapers.retry": "නැවත උත්සාහ කරන්න",
    "pastPapers.review": "නැවත බලන්න",
    "pastPapers.noResults": "ඔබේ පෙරහන්වලට ගැලපෙන ප්‍රශ්න පත්‍ර නොමැත",
    "pastPapers.papers": "ප්‍රශ්න පත්‍ර",
    "pastPapers.questions": "ප්‍රශ්න",

    // Challenge
    "challenge.title": "අභියෝග ප්‍රකාරය",
    "challenge.desc": "තත්‍ය කාලීන දැනුම සටන්වල වෙනත් සිසුන් සමඟ සටන් කරන්න",
    "challenge.findOpponent": "ප්‍රතිවාදියෙකු සොයන්න",
    "challenge.searching": "සුදුසු ප්‍රතිවාදියෙකු සොයමින්...",
    "challenge.opponentFound": "ප්‍රතිවාදියා හමු විය! සටන සූදානම් කරමින්...",
    "challenge.1v1": "1v1 දැනුම සටන",
    "challenge.you": "ඔබ",
    "challenge.opponent": "ප්‍රතිවාදියා",
    "challenge.question": "ප්‍රශ්නය",
    "challenge.victory": "ජයග්‍රහණය!",
    "challenge.defeat": "පරාජය",
    "challenge.draw": "සමානයි!",
    "challenge.outstanding": "විශිෂ්ට කාර්ය සාධනයක්!",
    "challenge.evenlyMatched": "සමාන මට්ටමක්!",
    "challenge.betterLuck": "ඊළඟ වතාවේ වාසනාව!",
    "challenge.playAgain": "නැවත ක්‍රීඩා කරන්න",
    "challenge.backToDashboard": "මුල් පිටුවට",
    "challenge.ratingPoints": "ශ්‍රේණිගත ලකුණු",
    "challenge.xpEarned": "ලබාගත් XP",

    // Leaderboard
    "leaderboard.title": "ලීඩර්බෝඩ්",
    "leaderboard.nationalTitle": "ජාතික ලීඩර්බෝඩ්",
    "leaderboard.compete": "ශ්‍රී ලංකාව පුරා සිසුන් 18,429 දෙනෙකු සමඟ තරඟ කරන්න",
    "leaderboard.desc": "ශ්‍රී ලංකාවේ ඉහළම උසස් පෙළ සිසුන් අතර ඔබේ ශ්‍රේණිය බලන්න",
    "leaderboard.national": "ජාතික",
    "leaderboard.school": "පාසල",
    "leaderboard.friends": "මිතුරන්",
    "leaderboard.searchStudents": "සිසුන් සොයන්න...",
    "leaderboard.rank": "ශ්‍රේණිය",
    "leaderboard.student": "සිසුවා",
    "leaderboard.score": "ලකුණු",
    "leaderboard.accuracy": "නිරවද්‍යතාව",
    "leaderboard.streak": "Streak",

    // Settings
    "settings.title": "සැකසුම්",
    "settings.desc": "ඔබේ පැතිකඩ, මනාපයන් සහ දැනුම්දීම් කළමනාකරණය කරන්න",
    "settings.profile": "පැතිකඩ",
    "settings.alerts": "දැනුම්දීම්",
    "settings.theme": "තේමාව",
    "settings.privacy": "පෞද්ගලිකත්වය",
    "settings.fullName": "සම්පූර්ණ නම",
    "settings.email": "විද්‍යුත් තැපෑල",
    "settings.school": "පාසල",
    "settings.phone": "දුරකථනය",
    "settings.stream": "විෂය ධාරාව",
    "settings.year": "වර්ෂය",
    "settings.saveChanges": "වෙනස්කම් සුරකින්න",
    "settings.savePreferences": "මනාපයන් සුරකින්න",
    "settings.applyChanges": "වෙනස්කම් යොදන්න",
    "settings.studyReminders": "අධ්‍යයන මතක් කිරීම්",
    "settings.studyRemindersDesc": "අපි ඔබට මතක් කරන්නේ කවදාද කෙසේද පාලනය කරන්න",
    "settings.dailyReminder": "දෛනික අධ්‍යයන මතක් කිරීම",
    "settings.dailyReminderDesc": "ඔබ කැමති අධ්‍යයන වේලාවට push දැනුම්දීමක් ලබන්න",
    "settings.weeklyReport": "සතිපතා ප්‍රගති වාර්තාව",
    "settings.weeklyReportDesc": "ඔබේ සතියේ කාර්ය සාධනයේ සාරාංශය",
    "settings.socialCompetitive": "සමාජ සහ තරඟකාරී",
    "settings.socialCompetitiveDesc": "මිතුරන් සහ ප්‍රතිවාදීන් සමඟ යාවත්කාලීනව සිටින්න",
    "settings.challengeInvites": "අභියෝග ආරාධනා",
    "settings.challengeInvitesDesc": "යමෙකු ඔබට සටනකට අභියෝග කළ විට",
    "settings.leaderboardUpdates": "ලීඩර්බෝඩ් යාවත්කාලීන",
    "settings.leaderboardUpdatesDesc": "ඔබේ ශ්‍රේණිය සැලකිය යුතු ලෙස වෙනස් වූ විට",
    "settings.deliveryChannels": "බෙදා හැරීමේ නාලිකා",
    "settings.emailNotifs": "විද්‍යුත් තැපැල් දැනුම්දීම්",
    "settings.pushNotifs": "Push දැනුම්දීම්",
    "settings.soundEffects": "ශබ්ද ප්‍රයෝග",
    "settings.themeLabel": "තේමාව",
    "settings.themeDesc": "ඔබේ දෘශ්‍ය විලාසය තෝරන්න",
    "settings.dark": "අඳුරු",
    "settings.darkDesc": "ඇස්වලට පහසුයි",
    "settings.light": "එළිය",
    "settings.lightDesc": "සම්භාව්‍ය දීප්තිමත් ප්‍රකාරය",
    "settings.system": "පද්ධතිය",
    "settings.systemDesc": "උපාංග සැකසුම් අනුගමනය කරන්න",
    "settings.language": "භාෂාව",
    "settings.languageDesc": "ප්‍රශ්න සහ UI සඳහා ඔබේ කැමති භාෂාව තෝරන්න",
    "settings.privacyVisibility": "පෞද්ගලිකත්වය සහ දෘශ්‍යතාව",
    "settings.privacyDesc": "ඔබේ දත්ත කවුද බලන්නේ කියා පාලනය කරන්න",
    "settings.showProfile": "ලීඩර්බෝඩ් එකේ පැතිකඩ පෙන්වන්න",
    "settings.showProfileDesc": "අනෙක් අය ඔබේ නම සහ පාසල දකී",
    "settings.showStreak": "Streak ප්‍රසිද්ධියේ පෙන්වන්න",
    "settings.showStreakDesc": "ඔබේ පැතිකඩේ ඔබේ streak පෙන්වන්න",
    "settings.allowChallenges": "අභියෝග ආරාධනා ඉඩ දෙන්න",
    "settings.allowChallengesDesc": "වෙනත් සිසුන්ට ඔබට අභියෝග කිරීමට ඉඩ දෙන්න",
    "settings.shareAnalytics": "ගුරුවරුන් සමඟ විශ්ලේෂණ බෙදාගන්න",
    "settings.shareAnalyticsDesc": "ඔබේ පාසලේ ගුරුවරුන්ට ඔබේ ප්‍රගතිය බැලිය හැක",
    "settings.dangerZone": "අන්තරාය කලාපය",
    "settings.dangerDesc": "මෙම ක්‍රියා ආපසු හැරවිය නොහැක",
    "settings.resetProgress": "ප්‍රගතිය යළි පිහිටුවන්න",
    "settings.deleteAccount": "ගිණුම මකන්න",

    // SubjectDetail
    "subjectDetail.stream": "ධාරාව",
    "subjectDetail.questions": "ප්‍රශ්න",
    "subjectDetail.accuracy": "නිරවද්‍යතාව",
    "subjectDetail.overview": "දළ විශ්ලේෂණය",
    "subjectDetail.chapters": "පරිච්ඡේද",
    "subjectDetail.practice": "පුහුණුව",
    "subjectDetail.pastPapers": "පසුගිය ප්‍රශ්න පත්‍ර",
    "subjectDetail.notes": "සටහන්",
    "subjectDetail.topicMasteryMap": "මාතෘකා ප්‍රවීණතා සිතියම",
    "subjectDetail.accuracyLast7": "නිරවද්‍යතාව — පසුගිය දින 7",
    "subjectDetail.subTopics": "උප මාතෘකා",
    "subjectDetail.configurePractice": "පුහුණු සැසිය වින්‍යාස කරන්න",
    "subjectDetail.chapter": "පරිච්ඡේදය",
    "subjectDetail.allChapters": "සියලු පරිච්ඡේද",
    "subjectDetail.difficulty": "දුෂ්කරතාව",
    "subjectDetail.questionType": "ප්‍රශ්න වර්ගය",
    "subjectDetail.mixed": "මිශ්‍ර",
    "subjectDetail.questionsCount": "ප්‍රශ්න",
    "subjectDetail.timedMode": "කාල සීමිත ප්‍රකාරය",
    "subjectDetail.beginPractice": "පුහුණුව ආරම්භ කරන්න",
    "subjectDetail.examination": "උසස් පෙළ විභාගය",
    "subjectDetail.startExam": "විභාගය ආරම්භ කරන්න",
    "subjectDetail.aiNotesSoon": "AI-ජනිත සාරාංශ සහ ප්‍රජා සටහන් ඉක්මනින්",
    "subjectDetail.qs": "ප්‍ර",

    // Practice
    "practice.questionOf": "ප්‍රශ්නය",
    "practice.of": "න්",
    "practice.excellentWork": "විශිෂ්ට කාර්යයක්!",
    "practice.goodJob": "හොඳ වැඩක්!",
    "practice.keepPracticing": "පුහුණුව දිගටම කරගෙන යන්න!",
    "practice.accuracy": "නිරවද්‍යතාව",
    "practice.correct": "නිවැරදි",
    "practice.wrong": "වැරදි",
    "practice.backToDashboard": "මුල් පිටුවට",
    "practice.tryAgain": "නැවත උත්සාහ කරන්න",
    "practice.explanation": "පැහැදිලි කිරීම",
    "practice.correctExplanation": "නිවැරදියි! හොඳයි. මෙය මෙම ගැටලුව විසඳීමේ නිවැරදි ප්‍රවේශයයි.",
    "practice.wrongExplanation": "වඩා හොඳ අවබෝධයක් සඳහා මෙම මාතෘකාව සමාලෝචනය කරන්න.",
    "practice.correctAnswerIs": "නිවැරදි පිළිතුර වන්නේ",
    "practice.flagForReview": "සමාලෝචනය සඳහා සලකුණු කරන්න",
    "practice.nextQuestion": "ඊළඟ ප්‍රශ්නය",
    "practice.finish": "අවසන් කරන්න",

    // Analytics
    "analytics.title": "විශ්ලේෂණ",
    "analytics.desc": "පසුගිය දින 30 තුළ ඔබේ කාර්ය සාධනය",
    "analytics.questionsAnswered": "පිළිතුරු දුන් ප්‍රශ්න",
    "analytics.overallAccuracy": "සමස්ත නිරවද්‍යතාව",
    "analytics.studyHours": "අධ්‍යයන පැය",
    "analytics.subjectsImproved": "වැඩි දියුණු වූ විෂයයන්",
    "analytics.accuracyBySubject": "විෂය අනුව නිරවද්‍යතාව",
    "analytics.dailyAccuracyTrend": "දෛනික නිරවද්‍යතා ප්‍රවණතාව",
    "analytics.topicMastery": "මාතෘකා ප්‍රවීණතාව",
    "analytics.studyActivity": "අධ්‍යයන ක්‍රියාකාරකම්",
    "analytics.examReadiness": "විභාග සූදානම",
    "analytics.examReady": "විභාගයට සූදානම්",
    "analytics.predictedGrades": "අපේක්ෂිත ලකුණු",
    "analytics.confidence": "විශ්වාසය",
    "analytics.less": "අඩු",
    "analytics.more": "වැඩි",
    "analytics.sessions": "සැසි",

    // Dashboard extra
    "dashboard.missedSessions": "ඔබ සැසි 3ක් මඟ හැරියා",
    "dashboard.chapter4": "පරිච්ඡේදය 4",
    "dashboard.accuracyDropped": "නිරවද්‍යතාව 69% දක්වා පහත වැටුණි",
    "dashboard.downFromLastWeek": "පසුගිය සතියට වඩා 75% සිට පහත",
    "dashboard.completedPhysics": "භෞතික විද්‍යාව MCQ කට්ටලය සම්පූර්ණ කළා — 18/20 නිවැරදි",
    "dashboard.newPersonalBest": "රසායන විද්‍යාවේ නව පුද්ගලික හොඳම! 94% නිරවද්‍යතාව",
    "dashboard.unlockedBadge": "අගුළු ඇරුණා: 'Week Warrior' ලාංඡනය",
    "dashboard.hoursAgo": "පැය 2කට පෙර",
    "dashboard.yesterday": "ඊයේ",
    "dashboard.daysAgo": "දින 3කට පෙර",
    "dashboard.paper1MCQs": "2022 ප්‍රශ්න පත්‍ර 1 MCQ",

    // Leaderboard extra
    "leaderboard.allSubjects": "සියලු විෂයයන්",
    "leaderboard.you": "ඔබ",
    "leaderboard.noData": "තවමත් ශ්‍රේණිගත කිරීම් නැත. ලීඩර්බෝඩ් එකේ පෙනෙන්න පුහුණු වන්න!",

    // Common
    "common.all": "සියල්ල",
    "common.easy": "පහසු",
    "common.medium": "මධ්‍යම",
    "common.hard": "අමාරු",
    "common.mcq": "MCQ",
    "common.structured": "ව්‍යුහගත",
    "common.essay": "රචනා",
    "common.english": "English",
    "common.sinhala": "සිංහල",
    "common.tamil": "தமிழ்",
  },

  ta: {
    // Nav
    "nav.home": "முகப்பு",
    "nav.subjects": "பாடங்கள்",
    "nav.practice": "பயிற்சி",
    "nav.pastPapers": "கடந்த வினாத்தாள்கள்",
    "nav.challenge": "சவால்",
    "nav.leaderboard": "தரவரிசை",
    "nav.analytics": "பகுப்பாய்வு",
    "nav.settings": "அமைப்புகள்",

    // Dashboard
    "dashboard.greeting": "காலை வணக்கம்",
    "dashboard.todaysPlan": "இன்றைய திட்டம்",
    "dashboard.questionsRemaining": "கேள்விகள் மீதமுள்ளன",
    "dashboard.startSession": "இன்றைய அமர்வைத் தொடங்கு",
    "dashboard.subjectUniverse": "பாட பிரபஞ்சம்",
    "dashboard.subjectUniverseDesc": "உங்கள் பாடங்கள் உங்கள் முன்னேற்றத்தைச் சுற்றி வட்டமிடுகின்றன",
    "dashboard.todaysQuestions": "இன்றைய கேள்விகள்",
    "dashboard.weeklyAccuracy": "வாராந்திர துல்லியம்",
    "dashboard.currentStreak": "தற்போதைய streak",
    "dashboard.nationalRank": "தேசிய தரவரிசை",
    "dashboard.recentActivity": "சமீபத்திய செயல்பாடு",
    "dashboard.needsAttention": "கவனம் தேவை",
    "dashboard.yourSubjects": "உங்கள் பாடங்கள்",
    "dashboard.practiceNow": "இப்போது பயிற்சி செய் →",
    "dashboard.reviewTopics": "தலைப்புகளை மறுபரிசீலனை செய் →",
    "dashboard.days": "நாட்கள்",
    "dashboard.daysToExam": "உ.த. பரீட்சைக்கு நாட்கள்",
    "dashboard.dayStreak": "நாள் streak",

    // Subjects
    "subject.combinedMaths": "கூட்டுக் கணிதம்",
    "subject.physics": "இயற்பியல்",
    "subject.chemistry": "வேதியியல்",
    "subject.biology": "உயிரியல்",
    "subject.integration": "தொகையீடு",
    "subject.wavesOptics": "அலைகள் & ஒளியியல்",
    "subjects.desc": "உங்கள் உ.த. பாடங்களை ஆராய்ந்து அத்தியாய அளவில் முன்னேற்றத்தைக் கண்காணிக்கவும்",
    "subjects.totalSubjects": "மொத்த பாடங்கள்",
    "subjects.totalChapters": "மொத்த அத்தியாயங்கள்",
    "subjects.totalQuestions": "மொத்த கேள்விகள்",
    "subjects.overallAccuracy": "ஒட்டுமொத்த துல்லியம்",
    "subjects.chapters": "அத்தியாயங்கள்",
    "subjects.questions": "கேள்விகள்",

    // Past Papers
    "pastPapers.title": "கடந்த வினாத்தாள்கள்",
    "pastPapers.desc": "முந்தைய ஆண்டுகளின் உண்மையான உ.த. பரீட்சை வினாத்தாள்களுடன் பயிற்சி செய்யுங்கள்",
    "pastPapers.totalPapers": "மொத்த வினாத்தாள்கள்",
    "pastPapers.attempted": "முயற்சித்தவை",
    "pastPapers.avgScore": "சராசரி மதிப்பெண்",
    "pastPapers.search": "பாடம், ஆண்டு அல்லது வகையால் தேடுங்கள்...",
    "pastPapers.starred": "நட்சத்திரமிட்டவை",
    "pastPapers.subject": "பாடம்",
    "pastPapers.year": "ஆண்டு",
    "pastPapers.type": "வகை",
    "pastPapers.start": "தொடங்கு",
    "pastPapers.retry": "மீண்டும் முயற்சி",
    "pastPapers.review": "மறுபரிசீலனை",
    "pastPapers.noResults": "உங்கள் வடிகட்டிகளுக்கு பொருந்தும் வினாத்தாள்கள் இல்லை",
    "pastPapers.papers": "வினாத்தாள்கள்",
    "pastPapers.questions": "கேள்விகள்",

    // Challenge
    "challenge.title": "சவால் பயன்முறை",
    "challenge.desc": "நிகழ்நேர அறிவுச் சண்டைகளில் மற்ற மாணவர்களுடன் போராடுங்கள்",
    "challenge.findOpponent": "எதிராளியைக் கண்டுபிடி",
    "challenge.searching": "தகுதியான எதிராளியைத் தேடுகிறது...",
    "challenge.opponentFound": "எதிராளி கண்டுபிடிக்கப்பட்டார்! சண்டையைத் தயாரிக்கிறது...",
    "challenge.1v1": "1v1 அறிவுச் சண்டை",
    "challenge.you": "நீங்கள்",
    "challenge.opponent": "எதிராளி",
    "challenge.question": "கேள்வி",
    "challenge.victory": "வெற்றி!",
    "challenge.defeat": "தோல்வி",
    "challenge.draw": "சமநிலை!",
    "challenge.outstanding": "சிறப்பான செயல்திறன்!",
    "challenge.evenlyMatched": "சமமான போட்டி!",
    "challenge.betterLuck": "அடுத்த முறை அதிர்ஷ்டம்!",
    "challenge.playAgain": "மீண்டும் விளையாடு",
    "challenge.backToDashboard": "முகப்புக்குத் திரும்பு",
    "challenge.ratingPoints": "தரமதிப்பு புள்ளிகள்",
    "challenge.xpEarned": "பெற்ற XP",

    // Leaderboard
    "leaderboard.title": "தரவரிசை",
    "leaderboard.nationalTitle": "தேசிய தரவரிசை",
    "leaderboard.compete": "இலங்கை முழுவதும் 18,429 மாணவர்களுடன் போட்டியிடுங்கள்",
    "leaderboard.desc": "இலங்கையின் சிறந்த உ.த. மாணவர்களிடையே உங்கள் தரவரிசையைப் பாருங்கள்",
    "leaderboard.national": "தேசிய",
    "leaderboard.school": "பாடசாலை",
    "leaderboard.friends": "நண்பர்கள்",
    "leaderboard.searchStudents": "மாணவர்களைத் தேடு...",
    "leaderboard.rank": "தரம்",
    "leaderboard.student": "மாணவர்",
    "leaderboard.score": "மதிப்பெண்",
    "leaderboard.accuracy": "துல்லியம்",
    "leaderboard.streak": "Streak",

    // Settings
    "settings.title": "அமைப்புகள்",
    "settings.desc": "உங்கள் சுயவிவரம், விருப்பங்கள் மற்றும் அறிவிப்புகளை நிர்வகிக்கவும்",
    "settings.profile": "சுயவிவரம்",
    "settings.alerts": "அறிவிப்புகள்",
    "settings.theme": "தீம்",
    "settings.privacy": "தனியுரிமை",
    "settings.fullName": "முழு பெயர்",
    "settings.email": "மின்னஞ்சல்",
    "settings.school": "பாடசாலை",
    "settings.phone": "தொலைபேசி",
    "settings.stream": "பாட பிரிவு",
    "settings.year": "ஆண்டு",
    "settings.saveChanges": "மாற்றங்களைச் சேமி",
    "settings.savePreferences": "விருப்பங்களைச் சேமி",
    "settings.applyChanges": "மாற்றங்களைப் பயன்படுத்து",
    "settings.studyReminders": "படிப்பு நினைவூட்டல்கள்",
    "settings.studyRemindersDesc": "நாங்கள் உங்களை எப்போது, எப்படி நினைவூட்டுவது என்பதைக் கட்டுப்படுத்தவும்",
    "settings.dailyReminder": "தினசரி படிப்பு நினைவூட்டல்",
    "settings.dailyReminderDesc": "நீங்கள் விரும்பும் படிப்பு நேரத்தில் push அறிவிப்பு பெறுங்கள்",
    "settings.weeklyReport": "வாராந்திர முன்னேற்ற அறிக்கை",
    "settings.weeklyReportDesc": "உங்கள் வாரத்தின் செயல்திறன் சுருக்கம்",
    "settings.socialCompetitive": "சமூக & போட்டி",
    "settings.socialCompetitiveDesc": "நண்பர்கள் மற்றும் போட்டியாளர்களுடன் புதுப்பித்தநிலையில் இருங்கள்",
    "settings.challengeInvites": "சவால் அழைப்புகள்",
    "settings.challengeInvitesDesc": "யாரேனும் உங்களுக்கு சவால் விடும்போது",
    "settings.leaderboardUpdates": "தரவரிசை புதுப்பிப்புகள்",
    "settings.leaderboardUpdatesDesc": "உங்கள் தரம் கணிசமாக மாறும்போது",
    "settings.deliveryChannels": "அனுப்பும் வழிகள்",
    "settings.emailNotifs": "மின்னஞ்சல் அறிவிப்புகள்",
    "settings.pushNotifs": "Push அறிவிப்புகள்",
    "settings.soundEffects": "ஒலி விளைவுகள்",
    "settings.themeLabel": "தீம்",
    "settings.themeDesc": "உங்கள் காட்சி பாணியைத் தேர்வுசெய்யுங்கள்",
    "settings.dark": "இருண்ட",
    "settings.darkDesc": "கண்களுக்கு எளிது",
    "settings.light": "ஒளிர்வான",
    "settings.lightDesc": "கிளாசிக் பிரகாசமான முறை",
    "settings.system": "கணினி",
    "settings.systemDesc": "சாதன அமைப்புகளைப் பின்பற்று",
    "settings.language": "மொழி",
    "settings.languageDesc": "கேள்விகள் மற்றும் UI க்கான உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்",
    "settings.privacyVisibility": "தனியுரிமை & காணும் தன்மை",
    "settings.privacyDesc": "உங்கள் தரவை யார் பார்க்கிறார்கள் என்பதைக் கட்டுப்படுத்தவும்",
    "settings.showProfile": "தரவரிசையில் சுயவிவரத்தைக் காட்டு",
    "settings.showProfileDesc": "மற்றவர்கள் உங்கள் பெயரையும் பாடசாலையையும் பார்க்கலாம்",
    "settings.showStreak": "Streak ஐ பகிரங்கமாகக் காட்டு",
    "settings.showStreakDesc": "உங்கள் சுயவிவரத்தில் உங்கள் streak ஐக் காட்டு",
    "settings.allowChallenges": "சவால் அழைப்புகளை அனுமதி",
    "settings.allowChallengesDesc": "மற்ற மாணவர்கள் உங்களுக்கு சவால் விட அனுமதிக்கவும்",
    "settings.shareAnalytics": "ஆசிரியர்களுடன் பகுப்பாய்வைப் பகிரவும்",
    "settings.shareAnalyticsDesc": "உங்கள் பாடசாலை ஆசிரியர்கள் உங்கள் முன்னேற்றத்தைப் பார்க்கலாம்",
    "settings.dangerZone": "ஆபத்து மண்டலம்",
    "settings.dangerDesc": "இந்த நடவடிக்கைகள் மீள முடியாதவை",
    "settings.resetProgress": "முன்னேற்றத்தை மீட்டமை",
    "settings.deleteAccount": "கணக்கை நீக்கு",

    // SubjectDetail
    "subjectDetail.stream": "பிரிவு",
    "subjectDetail.questions": "கேள்விகள்",
    "subjectDetail.accuracy": "துல்லியம்",
    "subjectDetail.overview": "கண்ணோட்டம்",
    "subjectDetail.chapters": "அத்தியாயங்கள்",
    "subjectDetail.practice": "பயிற்சி",
    "subjectDetail.pastPapers": "கடந்த வினாத்தாள்கள்",
    "subjectDetail.notes": "குறிப்புகள்",
    "subjectDetail.topicMasteryMap": "தலைப்பு திறன் வரைபடம்",
    "subjectDetail.accuracyLast7": "துல்லியம் — கடந்த 7 நாட்கள்",
    "subjectDetail.subTopics": "உள்-தலைப்புகள்",
    "subjectDetail.configurePractice": "பயிற்சி அமர்வை கட்டமைக்கவும்",
    "subjectDetail.chapter": "அத்தியாயம்",
    "subjectDetail.allChapters": "அனைத்து அத்தியாயங்கள்",
    "subjectDetail.difficulty": "சிரமம்",
    "subjectDetail.questionType": "கேள்வி வகை",
    "subjectDetail.mixed": "கலப்பு",
    "subjectDetail.questionsCount": "கேள்விகள்",
    "subjectDetail.timedMode": "நேர பயன்முறை",
    "subjectDetail.beginPractice": "பயிற்சியைத் தொடங்கு",
    "subjectDetail.examination": "உ.த. பரீட்சை",
    "subjectDetail.startExam": "பரீட்சையைத் தொடங்கு",
    "subjectDetail.aiNotesSoon": "AI-உருவாக்கிய சுருக்கங்கள் மற்றும் சமூக குறிப்புகள் விரைவில்",
    "subjectDetail.qs": "கே",

    // Practice
    "practice.questionOf": "கேள்வி",
    "practice.of": "ல்",
    "practice.excellentWork": "சிறப்பான வேலை!",
    "practice.goodJob": "நல்ல வேலை!",
    "practice.keepPracticing": "பயிற்சியைத் தொடருங்கள்!",
    "practice.accuracy": "துல்லியம்",
    "practice.correct": "சரி",
    "practice.wrong": "தவறு",
    "practice.backToDashboard": "முகப்புக்குத் திரும்பு",
    "practice.tryAgain": "மீண்டும் முயற்சி",
    "practice.explanation": "விளக்கம்",
    "practice.correctExplanation": "சரி! நன்று. இது இந்த சிக்கலை தீர்ப்பதற்கான சரியான அணுகுமுறை.",
    "practice.wrongExplanation": "சிறந்த புரிதலுக்கு இந்த தலைப்பை மறுபரிசீலனை செய்யுங்கள்.",
    "practice.correctAnswerIs": "சரியான பதில்",
    "practice.flagForReview": "மறுபரிசீலனைக்குக் குறி",
    "practice.nextQuestion": "அடுத்த கேள்வி",
    "practice.finish": "முடி",

    // Analytics
    "analytics.title": "பகுப்பாய்வு",
    "analytics.desc": "கடந்த 30 நாட்களில் உங்கள் செயல்திறன்",
    "analytics.questionsAnswered": "பதிலளிக்கப்பட்ட கேள்விகள்",
    "analytics.overallAccuracy": "ஒட்டுமொத்த துல்லியம்",
    "analytics.studyHours": "படிப்பு மணிநேரம்",
    "analytics.subjectsImproved": "மேம்பட்ட பாடங்கள்",
    "analytics.accuracyBySubject": "பாடம் வாரியாக துல்லியம்",
    "analytics.dailyAccuracyTrend": "தினசரி துல்லிய போக்கு",
    "analytics.topicMastery": "தலைப்பு திறன்",
    "analytics.studyActivity": "படிப்பு செயல்பாடு",
    "analytics.examReadiness": "பரீட்சை தயார்நிலை",
    "analytics.examReady": "பரீட்சைக்கு தயார்",
    "analytics.predictedGrades": "எதிர்பார்க்கப்படும் தரங்கள்",
    "analytics.confidence": "நம்பிக்கை",
    "analytics.less": "குறைவு",
    "analytics.more": "அதிகம்",
    "analytics.sessions": "அமர்வுகள்",

    // Dashboard extra
    "dashboard.missedSessions": "நீங்கள் 3 அமர்வுகளை தவறவிட்டீர்கள்",
    "dashboard.chapter4": "அத்தியாயம் 4",
    "dashboard.accuracyDropped": "துல்லியம் 69% ஆகக் குறைந்தது",
    "dashboard.downFromLastWeek": "கடந்த வாரத்தில் இருந்து 75% ல் இருந்து குறைந்தது",
    "dashboard.completedPhysics": "இயற்பியல் MCQ தொகுப்பை முடித்தது — 18/20 சரி",
    "dashboard.newPersonalBest": "வேதியியலில் புதிய சிறந்த சாதனை! 94% துல்லியம்",
    "dashboard.unlockedBadge": "திறக்கப்பட்டது: 'Week Warrior' பதக்கம்",
    "dashboard.hoursAgo": "2 மணி நேரத்திற்கு முன்",
    "dashboard.yesterday": "நேற்று",
    "dashboard.daysAgo": "3 நாட்களுக்கு முன்",
    "dashboard.paper1MCQs": "2022 வினாத்தாள் 1 MCQ",

    // Leaderboard extra
    "leaderboard.allSubjects": "அனைத்து பாடங்கள்",
    "leaderboard.you": "நீங்கள்",
    "leaderboard.noData": "இன்னும் தரவரிசைகள் இல்லை. தரவரிசையில் தோன்ற பயிற்சி செய்யுங்கள்!",

    // Common
    "common.all": "அனைத்தும்",
    "common.easy": "எளிது",
    "common.medium": "நடுத்தரம்",
    "common.hard": "கடினம்",
    "common.mcq": "MCQ",
    "common.structured": "கட்டமைக்கப்பட்ட",
    "common.essay": "கட்டுரை",
    "common.english": "English",
    "common.sinhala": "සිංහල",
    "common.tamil": "தமிழ்",
  },
};
